### PR TITLE
Berkay week 1 tasks

### PR DESCRIPTION
**Pull request by dikicier**
i have completed week 1 group 3 tasks
plse check and advice

### CODE REVIEW

**Review by ElifEbrar — APPROVED** [review]
Looks good

**Comment by bilalkoca** [comment]
It is ok,

**Comment by bilalkoca** [comment]
It is OK

**Review by bilalkoca — COMMENTED** [review]
It is OK

**Review by bilalkoca — COMMENTED** [review]
It is OK

**Review by bilalkoca — COMMENTED** [review]
It is OK.

**Review by bilalkoca — COMMENTED** [review]
OK

**Comment by bilalkoca** [comment]
OK

**Pull request merged**
